### ISSUE TITLE
About Shape and Dimension Errors

### ISSUE THREAD

**Issue by 7unahan** [NX-AI/vision-lstm#10]
First of all, thanks for this excellent work.

I tried your model with a random torch and it worked. After that, I tried the bigger model to train the CIFAR10 dataset. I add a few linear, norm layers, etc. but it gives math shapes error continuously. When I solve one, it breaks another one. Is there any guide for a simple classification study for your model?

I appreciate any help you can provide.

**Comment by BenediktAlkin** [comment]
If you change stuff in the architecture, you'll have to debug that yourself.

I added a tutorial on how to train a model on CIFAR10, hope that helps.
