### ISSUE TITLE
I am very interested in your method and would like to know how to apply this model to segmentation tasks?

### ISSUE THREAD

**Issue by chord1412077** [NX-AI/vision-lstm#12]
I am very interested in your method and would like to know how to apply this model to segmentation tasks?

**Comment by BenediktAlkin** [comment]
We apply our model to ADE20K segmentation in the same way as common ViT pipelines. The yaml files which we used for the segmentation tasks in the paper can be found [here](https://github.com/NX-AI/vision-lstm/tree/main/src/vislstm/yamls/segmentation). These configurations follow a common UperNet ViT segmentation pipeline.

There are also already some works that use ViL for medical segmentation where they use some ViL blocks after some convolution layers. [work1](https://arxiv.org/abs/2406.16993) [work2](https://arxiv.org/abs/2407.01530)
