### ISSUE TITLE
How to train with your own dataset?

### ISSUE THREAD

**Issue by chord1412077** [NX-AI/vision-lstm#13]
Thanks a lot!
How to train with my own dataset?

**Comment by BenediktAlkin** [comment]
either implement it into the codebase like [the other datasets](https://github.com/NX-AI/vision-lstm/tree/main/src/vislstm/datasets) or use the [standalone](https://github.com/NX-AI/vision-lstm/tree/main/vision_lstm) implementation and implement your own pipeline
