### ISSUE TITLE
Concerns about ViL for target detection

### ISSUE THREAD

**Issue by WangYoung7** [NX-AI/vision-lstm#15]
Target detection is also an important part of computer vision, do you have plans for his adaptation? Thank you!

**Comment by BenediktAlkin** [comment]
Target detection is not a common benchmark in CV papers, so we are not planning on adapting ViL to that task. However, we published all models and code, so you are free to adapt it yourself to your use-case.

If you mean object detection, we do plan to include it, once we have cuda kernels for ViL.

**Comment by WangYoung7** [comment]
thank you！
