### ISSUE TITLE
question and bug

### ISSUE THREAD

**Issue by xty-11** [NX-AI/vision-lstm#18]
Hello, I would like to use the file 'view_1stm2.py' as my backbone to extract features (I don't need its final head layer for classification). I encountered a keyword mismatch or non-existent issue while loading the weight file. How can I modify the code to use your 'view_1stm/vil2.base16-e400_in1k. th' weight file
![微信图片_20240929115739](https://github.com/user-attachments/assets/f78e689e-f880-4bc8-bd42-63e493e8b770)
If you could reply, I would greatly appreciate it!

**Comment by BenediktAlkin** [comment]
VisionLSTM2 is a cleaned version of what we used to train our models. The names of the weights were changed and blocks were merged to be block pairs for easier compatibility with ViT pipelines. Therefore you need to rename weights. This is done in the hubconf.py and automatically done if you load the model as it is instructed in the README via `torch.hub.load`.

**Comment by xty-11** [comment]
> VisionLSTM2 是我们用来训练模型的简化版本。权重的名称被更改，区块被合并为区块对，以便更容易地与 ViT 管道兼容。因此，您需要重命名权重。此操作在 hubconf.py 中完成，如果您按照 README 中的指示加载模型，则会自动完成。`torch.hub.load`

Thank you, my issue has been resolved!
