### ISSUE TITLE
Difference between causal1d and SequenceConv2d

### ISSUE THREAD

**Issue by StarPlatinumDa** [NX-AI/vision-lstm#19]
As in the title, I find that SequenceConv2d is used instead of causal1d. And causal1d is used in the original code of x-lstm. I wonder what is the difference between them. I use the block in my code and find that causal1d is lower with fewer parameters, but the final result is not so good as SequenceConv2d. So I come up with this question. Is it something we can only know after training or there has some scientific reasons? Thank you for your answering.

**Comment by BenediktAlkin** [comment]
language modeling is a causal task on 1d data, so if you want to aggregate local context a causal1d convolution can be used for that. Images are 2D data and there is no causal structure, so the SequenceConv2D simply transforms the flattened image patches back into an image shape and does a Conv2d on it before flattening it again. This allows the model to aggregate local information better.

**Comment by StarPlatinumDa** [comment]
> language modeling is a causal task on 1d data, so if you want to aggregate local context a causal1d convolution can be used for that. Images are 2D data and there is no causal structure, so the SequenceConv2D simply transforms the flattened image patches back into an image shape and does a Conv2d on it before flattening it again. This allows the model to aggregate local information better.
Thanks a lot!
