### ISSUE TITLE
Comparision with VisionLSTM-Out

### ISSUE THREAD

**Issue by bio-mlhui** [NX-AI/vision-lstm#2]
Mamba and xLSTM are both RNN models, what is the Imagenet1k-acc if the Lstm transform are removed?

**Comment by BenediktAlkin** [comment]
The surrounding components of the Mamba SSM and the mLSTM cells are really similar (up projection -> SSM/mLSTM -> gated MLP -> downprojection -> skip connection) so VisionLSTM-Out would be more or less equivalent to Mamba-Out.
