### ISSUE TITLE
Questions about training accuracy

### ISSUE THREAD

**Issue by xty-11** [NX-AI/vision-lstm#21]
Hello author!
I use your vision_lstm2.py as a backbone for the task of domain generalized person re-identification. During training, the mAP of the network reaches its highest point in the second epoch, and then becomes lower. Normally, mAP requires 10-20 rounds of learning to achieve good results. I can't figure out what's wrong.
I would like to ask, has your team encountered similar problems in research? Or do you have any similar experience? I'd like to hear your opinion.
Looking forward to your answer!
The following is the change chart of mAP and epoch
![image](https://github.com/user-attachments/assets/e37821d3-a81d-49d7-8e87-a191887a47b9)

**Comment by BenediktAlkin** [comment]
Hi, TBH I never worked with that specific task so its hard to give any advice on it. 
The curve looks like the model is already in an overfitting regime, so you would need to increase regularization (e.g. stochastic depth). Maybe plot training mAP over test mAP and check if the model is overfitting.

I've never faced something similar on ImageNet, but it's also quite hard to overfit on ImageNet with the right stochastic depth and image augmentations.

**Comment by xty-11** [comment]
Thank you very much for your suggestion. I will refer to your suggestion to troubleshoot this issue.I wish you good luck with your research!
