### ISSUE TITLE
Typo in Table 1 from Paper

### ISSUE THREAD

**Issue by willxxy** [NX-AI/vision-lstm#3]
Hello, 

Thank you for the awesome work. While going through the paper, I found that in Table 1, there seems to be a typo in the following statement "Entries in gray are trained trained for 400 epochs more than ViL."

I wanted to bring this to your attention. If this was intentional, would you mind clarifying the meaning of "trained trained?"

Thank you! I attached a screenshot of it as well.

<img width="721" alt="Screenshot 2024-06-07 at 5 32 44 PM" src="https://github.com/NX-AI/vision-lstm/assets/90741489/fb048528-c412-4078-9c11-04e6f7b56bfa">

**Comment by BenediktAlkin** [comment]
Hi, thanks for reading it carefully and pointing that out. 
It's not intentional, just a case of [repetition blindness](https://en.wikipedia.org/wiki/Repetition_blindness) :)
Well fix that in the next version.
