### ISSUE TITLE
about parallelization of mlstm

### ISSUE THREAD

**Issue by xxyh1993** [NX-AI/vision-lstm#9]
I don't understand ‘Parallel mLSTM Forward Pass’ at all. Could you explain how it became parallel？Furthermore，mLSTM is O(n^2) computation w.r.t the dim of input, why is this depicted  as linear in papers?

**Comment by xxyh1993** [comment]
Thank you for your help！

**Comment by BenediktAlkin** [comment]
The mLSTM has a parallel mode which calculates a QK matrix which has NxN, therefore making it O(N^2D) with seqlence length N and dimension D. You can imagine it as "calculate all hidden state updates from the inputs only and only then integrate it into the hidden state". This is the mode we train our models in and calculate FLOPS for.

However, the mLSTM also has a recurrent mode, which "updates the hidden states step-by-step" similar to how a vanilla LSTM works. This results in complexity O(ND^2), i.e. linear in sequence length.

You can also combine these modes into a "chunkwise" mode.

So for long sequences, you would use a chunkwise or recurrent formulation of the mLSTM, which results in linear complexity w.r.t. sequence length.

For more information see the [xLSTM paper](https://arxiv.org/abs/2405.04517) or [GLA](https://arxiv.org/abs/2312.06635) which is also a linear complexity model with a similar complexity tradeoff as the mLSTM
